#define e "e"
#define ee int
#define eee char
#define eeee void
#define eeeee float
#define eeeeee long
#define eeeeeee short
#define eeeeeeee double
#define eeeeeeeee enum
#define eeeeeeeeee main
#define eeeeeeeeeee printf
#define eeeeeeeeeeee for
#define eeeeeeeeeeeee while
#define eeeeeeeeeeeeee do
#define eeeeeeeeeeeeeee 1
#define eeeeeeeeeeeeeeee 0
#define eeeeeeeeeeeeeeeee if
#define eeeeeeeeeeeeeeeeee else
#define eeeeeeeeeeeeeeeeeee switch
#define eeeeeeeeeeeeeeeeeeee case
#define eeeeeeeeeeeeeeeeeeeee default
#define eeeeeeeeeeeeeeeeeeeeee continue
#define eeeeeeeeeeeeeeeeeeeeeee break
#define eeeeeeeeeeeeeeeeeeeeeeee return
#define eeeeeeeeeeeeeeeeeeeeeeeee typedef
#define eeeeeeeeeeeeeeeeeeeeeeeeee struct
#define eeeeeeeeeeeeeeeeeeeeeeeeeee union
#define eeeeeeeeeeeeeeeeeeeeeeeeeeee static
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeee auto
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeee const
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee extern
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee signed
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee unsigned
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee restrict
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee inline
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee volatile
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee goto
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee (
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee )
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee {
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee }
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee ;
