#define e "e"
#define ee int
#define eee char
#define eeee void
#define eeeee float
#define eeeeee long
#define eeeeeee short
#define eeeeeeee double
#define eeeeeeeee enum
#define eeeeeeeeee main
#define eeeeeeeeeee printf
#define eeeeeeeeeeee for
#define eeeeeeeeeeeee while
#define eeeeeeeeeeeeee do
#define eeeeeeeeeeeeeee 1
#define eeeeeeeeeeeeeeee 0
#define eeeeeeeeeeeeeeeee if
#define eeeeeeeeeeeeeeeeee else
#define eeeeeeeeeeeeeeeeeee switch
#define eeeeeeeeeeeeeeeeeeee case
#define eeeeeeeeeeeeeeeeeeeee default
#define eeeeeeeeeeeeeeeeeeeeee continue
#define eeeeeeeeeeeeeeeeeeeeeee break
#define eeeeeeeeeeeeeeeeeeeeeeee return
#define eeeeeeeeeeeeeeeeeeeeeeeee typedef
#define eeeeeeeeeeeeeeeeeeeeeeeeee struct
#define eeeeeeeeeeeeeeeeeeeeeeeeeee static
#define eeeeeeeeeeeeeeeeeeeeeeeeeeee const
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeee signed
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeee unsigned
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee inline
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee goto
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee (
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee )
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee {
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee }
#define eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee ;
#define E union
#define Ee auto
#define Eee extern
#define Eeee restrict
#define Eeeee volatile